### ISSUE TITLE
FFMpegInterop with GDXVideo

### ISSUE THREAD

**Issue by SonicACCEL** [libgdx/gdx-video#26]
Curious if there's any benefit to FFMpegInterop ( https://github.com/Microsoft/FFmpegInterop ) GDXVideo bindings? 

On desktop, is the windows media pipeline inherently superior?

**Comment by Robbiedobbie** [comment]
It doesn't look like it gives any advantages over ffmpeg compiled with HWA codecs.
It might also introduce bugs on windows only, so I'm not a big fan, given the 2 minutes that I looked into it. (So I might be wrong)

In my opinion the windows media pipeline is one mess with codecs working on one pc, and not on the next. This however is my opinion, so you can probably find someone on the internet that thinks differently.

I'm closing this issue because there are no plans for integrating this. If gdx-video should ever work on windows phone (Because libgdx suddenly supports windows phone), I might look into it.
