### ISSUE TITLE
Minimum SDK supported?

### ISSUE THREAD

**Issue by gamedev263** [libgdx/gdx-video#49]
I couldn't find anywhere what the minimum device API this library supports? I am only asking since I'm having some issues with playback on lower API emulators, but it seems work on actual devices.

**Comment by Robbiedobbie** [comment]
Gdx-video needs API version 12 or higher. However, on higher versions the emulator support is iffy to say the least. This is because the android version uses SurfaceTextures in order to not have to copy each frame into a new texture, saving a lot of bandwidth on the GPU. The emulator doesn't seem to correctly support this on all versions.
